# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Windows2.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Windows3_ui import Ui_Dialog1
from random import*

class Ui_Dialog(object):

    def selesai(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = Ui_Dialog1()
        self.ui.setupUi(self.Dialog)
        Dialog.hide()
        self.Dialog.show()

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1366, 786)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(230, 320, 47, 13))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, -10, 1001, 801))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../../../Users/Dika/Videos/516554842.jpg"))
        self.label_2.setObjectName("label_2")
        self.radioButton1 = QtWidgets.QRadioButton(Dialog)
        self.radioButton1.setGeometry(QtCore.QRect(430, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton1.setFont(font)
        self.radioButton1.setObjectName("radioButton1")
        self.radioButton2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton2.setGeometry(QtCore.QRect(560, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton2.setFont(font)
        self.radioButton2.setObjectName("radioButton2")
        self.labelNama = QtWidgets.QLabel(Dialog)
        self.labelNama.setGeometry(QtCore.QRect(160, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelNama.setFont(font)
        self.labelNama.setObjectName("labelNama")
        self.txtUmur = QtWidgets.QLineEdit(Dialog)
        self.txtUmur.setGeometry(QtCore.QRect(430, 150, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtUmur.setFont(font)
        self.txtUmur.setText("")
        self.txtUmur.setObjectName("txtUmur")
        self.labelUmur = QtWidgets.QLabel(Dialog)
        self.labelUmur.setGeometry(QtCore.QRect(160, 150, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelUmur.setFont(font)
        self.labelUmur.setObjectName("labelUmur")
        self.labelGender = QtWidgets.QLabel(Dialog)
        self.labelGender.setGeometry(QtCore.QRect(160, 110, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelGender.setFont(font)
        self.labelGender.setObjectName("labelGender")
        self.txtTinggi = QtWidgets.QLineEdit(Dialog)
        self.txtTinggi.setGeometry(QtCore.QRect(430, 230, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtTinggi.setFont(font)
        self.txtTinggi.setObjectName("txtTinggi")
        self.labelTinggi = QtWidgets.QLabel(Dialog)
        self.labelTinggi.setGeometry(QtCore.QRect(160, 220, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelTinggi.setFont(font)
        self.labelTinggi.setObjectName("labelTinggi")
        self.txtNama = QtWidgets.QLineEdit(Dialog)
        self.txtNama.setGeometry(QtCore.QRect(430, 60, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtNama.setFont(font)
        self.txtNama.setText("")
        self.txtNama.setObjectName("txtNama")
        self.labelKg = QtWidgets.QLabel(Dialog)
        self.labelKg.setGeometry(QtCore.QRect(500, 190, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelKg.setFont(font)
        self.labelKg.setObjectName("labelKg")
        self.txtBerat = QtWidgets.QLineEdit(Dialog)
        self.txtBerat.setGeometry(QtCore.QRect(430, 190, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtBerat.setFont(font)
        self.txtBerat.setObjectName("txtBerat")
        self.labelBerat = QtWidgets.QLabel(Dialog)
        self.labelBerat.setGeometry(QtCore.QRect(160, 190, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelBerat.setFont(font)
        self.labelBerat.setObjectName("labelBerat")
        self.labelAktiv = QtWidgets.QLabel(Dialog)
        self.labelAktiv.setGeometry(QtCore.QRect(160, 260, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelAktiv.setFont(font)
        self.labelAktiv.setObjectName("labelAktiv")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(430, 260, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.labelCm = QtWidgets.QLabel(Dialog)
        self.labelCm.setGeometry(QtCore.QRect(500, 230, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelCm.setFont(font)
        self.labelCm.setObjectName("labelCm")
        self.labelData = QtWidgets.QLabel(Dialog)
        self.labelData.setGeometry(QtCore.QRect(560, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelData.setFont(font)
        self.labelData.setObjectName("labelData")
        self.labelHasil = QtWidgets.QLabel(Dialog)
        self.labelHasil.setGeometry(QtCore.QRect(190, 390, 761, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelHasil.setFont(font)
        self.labelHasil.setObjectName("labelHasil")
        self.btnPrint = QtWidgets.QPushButton(Dialog)
        self.btnPrint.setGeometry(QtCore.QRect(640, 320, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnPrint.setFont(font)
        self.btnPrint.setObjectName("btnPrint")
        self.btnClear = QtWidgets.QPushButton(Dialog)
        self.btnClear.setGeometry(QtCore.QRect(750, 320, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.labelKcal2 = QtWidgets.QLabel(Dialog)
        self.labelKcal2.setGeometry(QtCore.QRect(550, 520, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelKcal2.setFont(font)
        self.labelKcal2.setObjectName("labelKcal2")
        self.txtKalori = QtWidgets.QLineEdit(Dialog)
        self.txtKalori.setGeometry(QtCore.QRect(470, 480, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtKalori.setFont(font)
        self.txtKalori.setObjectName("txtKalori")
        self.labelKalori = QtWidgets.QLabel(Dialog)
        self.labelKalori.setGeometry(QtCore.QRect(200, 480, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelKalori.setFont(font)
        self.labelKalori.setObjectName("labelKalori")
        self.labelOlahraga = QtWidgets.QLabel(Dialog)
        self.labelOlahraga.setGeometry(QtCore.QRect(800, 550, 81, 21))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelOlahraga.setFont(font)
        self.labelOlahraga.setObjectName("labelOlahraga")
        self.labelTips = QtWidgets.QLabel(Dialog)
        self.labelTips.setGeometry(QtCore.QRect(200, 560, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelTips.setFont(font)
        self.labelTips.setObjectName("labelTips")
        self.labelKcal1 = QtWidgets.QLabel(Dialog)
        self.labelKcal1.setGeometry(QtCore.QRect(550, 480, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelKcal1.setFont(font)
        self.labelKcal1.setObjectName("labelKcal1")
        self.labelTotal = QtWidgets.QLabel(Dialog)
        self.labelTotal.setGeometry(QtCore.QRect(200, 520, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelTotal.setFont(font)
        self.labelTotal.setObjectName("labelTotal")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(710, 570, 251, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(470, 570, 211, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.labelMakanan = QtWidgets.QLabel(Dialog)
        self.labelMakanan.setGeometry(QtCore.QRect(530, 550, 81, 21))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelMakanan.setFont(font)
        self.labelMakanan.setObjectName("labelMakanan")
        self.txtTotal = QtWidgets.QLineEdit(Dialog)
        self.txtTotal.setGeometry(QtCore.QRect(470, 520, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtTotal.setFont(font)
        self.txtTotal.setObjectName("txtTotal")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(880, 730, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(1000, -10, 371, 801))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../../../Users/Dika/Pictures/516554842.jpg"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(70, 370, 111, 101))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../../../../Users/Dika/Pictures/800px_COLOURBOX22291869.jpg"))
        self.label_5.setObjectName("label_5")

        self.btnClear.clicked.connect(self.bersihkan)
        self.btnPrint.clicked.connect(self.processInputs)
        self.pushButton.clicked.connect(self.selesai)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton1.setText(_translate("Dialog", "Laki-laki"))
        self.radioButton2.setText(_translate("Dialog", "Perempuan"))
        self.labelNama.setText(_translate("Dialog", "Nama"))
        self.labelUmur.setText(_translate("Dialog", "Umur"))
        self.labelGender.setText(_translate("Dialog", "Jenis Kelamin"))
        self.labelTinggi.setText(_translate("Dialog", "Tinggi Badan"))
        self.labelKg.setText(_translate("Dialog", "Kg"))
        self.labelBerat.setText(_translate("Dialog", "Berat Badan"))
        self.labelAktiv.setText(_translate("Dialog", "Aktivitas"))
        self.comboBox.setItemText(0, _translate("Dialog", "Aktivitas Ringan"))
        self.comboBox.setItemText(1, _translate("Dialog", "Aktivitas Normal"))
        self.comboBox.setItemText(2, _translate("Dialog", "Aktivitas Berat"))
        self.comboBox.setItemText(3, _translate("Dialog", "Aktivitas Sangat Berat"))
        self.comboBox.setItemText(4, _translate("Dialog", "Tidak Aktif"))
        self.labelCm.setText(_translate("Dialog", "Cm"))
        self.labelData.setText(_translate("Dialog", "Data"))
        self.labelHasil.setText(_translate("Dialog", "Berdasarkan data yang anda masukkan, berikut adalah kebutuhan kalori yang\n"
"dibutuhkan tubuh anda"))
        self.btnPrint.setText(_translate("Dialog", "Scan"))
        self.btnClear.setText(_translate("Dialog", "Clear"))
        self.labelKcal2.setText(_translate("Dialog", "Kcal"))
        self.labelKalori.setText(_translate("Dialog", "Kebutuhan Kalori/Hari"))
        self.labelOlahraga.setText(_translate("Dialog", "Olahraga"))
        self.labelTips.setText(_translate("Dialog", "Rekomendasi"))
        self.labelKcal1.setText(_translate("Dialog", "Kcal"))
        self.labelTotal.setText(_translate("Dialog", "Kebutuhan Kalori Total"))
        self.labelMakanan.setText(_translate("Dialog", "Makanan"))
        self.pushButton.setText(_translate("Dialog", "SELESAI"))

    def bersihkan(self):
        self.txtNama.setText("")
        self.txtUmur.setText("")
        self.txtBerat.setText("")
        self.txtTinggi.setText("")
        self.txtKalori.setText("")
        self.txtTotal.setText("")
        self.plainTextEdit.clear()
        self.plainTextEdit_2.clear()
        self.txtNama.setFocus()
 
    def processInputs(self):
        Makanan = ['Telur','Ikan Salmon','Ikan Tuna','Dada Ayam','Jamur Matsutake','Kerang Tiram','Yougurt','Beras Merah','Oatmeal','Singkong','Jagung','Kentang','Talas','Ubi Jalar','Brokoli','Wortel','Bayam','Asparagus','Kacang-kacangan','Cabe','Buncis','Kubis']
        Buah = ['Jeruk Lemon','Pepaya','Pear','Apel','Pisang','Alpukat','Blueberry','Tomat','Mangga','Kelapa']
        Olahraga = ['Lompat Tali selama 10 menit ','Aerobik selama 15 menit','Berenang selama 30 menit','Berlari 60 menit','Bersepeda selama 30 menit','Squat Jump selama 20 menit','Push Up selama 10 menit','Pull Up selama 15 menit','Squat Thrust selama 10 menit','Sit Up selama 15 menit']
        a= float(self.txtUmur.text())
        b= float(self.txtBerat.text())
        c= float(self.txtTinggi.text())
        bmr=0
        ringan=0
        Kalori=2500
        
        if self.radioButton1.isChecked()==True:
            bmr= float(round (66 + (13.7 * b) + (5 * c) - (6.8 - a)))
            self.txtKalori.setText(str(bmr))
        else :
            bmr= float (round(655 + (9.6 * b) + (1.8 * c) - (4.7 - a)))
            self.txtKalori.setText(str(bmr))
    
        if self.comboBox.currentText() =="Aktivitas Ringan":
            ringan=float(round(1.375*bmr))
            self.txtTotal.setText(str(ringan))
        elif self.comboBox.currentText()=="Aktivitas Normal":
            ringan=float(round(1.55*bmr))
            self.txtTotal.setText(str(ringan))
        elif self.comboBox.currentText()=="Aktivitas Berat":
            ringan=float(round(1.725*bmr))
            self.txtTotal.setText(str(ringan))
        elif self.comboBox.currentText()=="Aktivitas Sangat Berat":
            ringan=float(round(1.9*bmr))
            self.txtTotal.setText(str(ringan))
        elif self.comboBox.currentText()=="Tidak Aktif":
            ringan=float(round(1.2*bmr))
            self.txtTotal.setText(str(ringan))
        
        jumlah_sayuran=len(Makanan)
        jumlah_buah=len(Buah)
        jumlah_daging=len(Olahraga)

        if (Kalori <= bmr ):
            advices = sample(Makanan, 5)
            for items in advices:
                self.plainTextEdit.appendPlainText(items)

            add = sample (Buah, 4)
            for item in add:
                self.plainTextEdit.appendPlainText(item)
            self.plainTextEdit_2.appendPlainText("Anda harus melakukan olahraga :")
            add = sample (Olahraga, 3,)
            for item in add:
                self.plainTextEdit_2.appendPlainText('Anda harus melakukan olahraga : ')
            
        else:
            (Kalori >= bmr )
            advices = sample(Makanan, 3)
            for items in advices:
                self.plainTextEdit.appendPlainText(items)

            add = sample (Buah, 4)
            for item in add:
                self.plainTextEdit.appendPlainText(item)
            self.plainTextEdit_2.appendPlainText("Anda harus melakukan olahraga :")
            add = sample (Olahraga, 5)
            for item in add:
                self.plainTextEdit_2.appendPlainText(item)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

